@startuml

rectangle "Client" as client

node "OpenSuse Tumbleweed (Linux)" as os {
  
  [Apache Web Server] as apache
  [PHP Scripts] as php
  database "mariadb" as mariadb
  [External API Calls] as api
}

client --> apache
apache --> php
php --> mariadb
mariadb --> php
php --> apache
apache --> api
api --> apache
apache --> client

@enduml
