FROM php:8.2-cli

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y git unzip \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./app /var/www/html
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

EXPOSE 8081
CMD ["php", "/var/www/html/websocket-server.php"]
