version: "3.9"

services:
  php-apache:
    build: .
    container_name: CodeTogetherServer
    ports:
      - "8080:80"
      - "8060:8060"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: America/Chicago
      MARIADB_INITDB_SKIP_TZINFO: 0 
    ports:
      - "3305:3306"
    volumes:
      - ./mariadb/mariadb-data:/var/lib/mysql
      - ./mariadb/mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
