version: "3.9"

services:
  php-apache:
    build: .
    container_name: CodeTogetherServer
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
      - websocket
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - ./mariadb/mariadb-data:/var/lib/mysql
      - ./mariadb/mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: websocket-server
    working_dir: /var/www/html
    ports:
      - "8081:8081"
    networks:
      - app-network
    volumes:
      - ./app:/var/www/html
      - /var/www/html/vendor  
    depends_on:
      - mariadb


networks:
  app-network:
    driver: bridge
