@startuml

scale 3

skinparam rectangle {
  BorderColor SteelBlue
  BackgroundColor SkyBlue
}

skinparam storage {
  BorderColor SteelBlue
  BackgroundColor SkyBlue
}


rectangle "User / Client" as User
storage "User Authentication" as UserAuth
rectangle "User DB" as UserDB
rectangle "Role DB" as RoleDB
storage "Serve User Feed" as Feed
rectangle "Post DB" as PostDB
rectangle "Message DB" as MessageDB
storage "Message Processing" as Message
storage "Coding Game" as Code

User -up-> UserAuth : Login\nrequest
UserAuth -down-> User : Confirm\nlogin

UserAuth -right-> UserDB : check for user

UserDB -right-> RoleDB : check for roles

RoleDB -left-> UserAuth : \nconfirm role and user

User -left-> Feed : request feed
Feed -right-> User : return user feed

Feed -up-> PostDB : request posts\n related to user
PostDB -down-> Feed : confirm user\n related posts

User -right-> Message : send messages to users
Message -left-> User : return conversation history

Message -right-> MessageDB : add to conversation history
MessageDB -left-> Message : return conversation history

User <-down-> Code : send \ recieve game state




@enduml
